CREATE SEQUENCE SURVEYEE_QUESTIONS_ANSWERS_PK_SEQ START WITH 1;  

CREATE TABLE SURVEYEE_QUESTIONS_CHOICES_ANSWERS_COUNT
(
	ID              	      	    INT8 NOT NULL,
    SURVEY_ID            	  	    INT8 NOT NULL,
    SURVEY_VERSION            	    INT8 NOT NULL,
    SURVEY_QUSTION_ID               INT8 NOT NULL,
    SURVEY_QUSTION_CHOICE_ID        INT8 NOT NULL,
    SURVEY_QUSTION_CHOICE_COUNT     INT8 NOT NULL DEFAULT 1

);



CREATE INDEX SURVEYEE_QUESTIONS_ANSWERS_SURVEY_ID_IDX ON SURVEYEE_QUESTIONS_CHOICES_ANSWERS_COUNT(SURVEY_ID);
CREATE INDEX SURVEYEE_QUESTIONS_ANSWERS_SURVEY_ID_VERSION_IDX ON SURVEYEE_QUESTIONS_CHOICES_ANSWERS_COUNT(SURVEY_ID,SURVEY_VERSION);
CREATE INDEX SURVEYEE_QUESTIONS_ANSWERS_SURVEY_QUSTION_ID_IDX ON SURVEYEE_QUESTIONS_CHOICES_ANSWERS_COUNT(SURVEY_QUSTION_ID);
CREATE INDEX SURVEYEE_QUESTIONS_ANSWERS_SURVEY_QUSTION_CHOICE_ID_IDX ON SURVEYEE_QUESTIONS_CHOICES_ANSWERS_COUNT(SURVEY_QUSTION_ID,SURVEY_QUSTION_CHOICE_ID);
CREATE INDEX SURVEYEE__VERSION_QUESTIONS_ANSWERS_SURVEY_QUSTION_CHOICE_ID_IDX ON SURVEYEE_QUESTIONS_CHOICES_ANSWERS_COUNT(SURVEY_ID,SURVEY_VERSION,SURVEY_QUSTION_ID,SURVEY_QUSTION_CHOICE_ID);